-- ============================================================
-- GirlTea App — Group slugs (readable URLs)
-- ============================================================
-- The web app routes groups by a human-readable slug (/college-girls)
-- rather than a UUID. Group names have spaces and aren't unique, so we
-- derive a URL-safe slug from the name, guarantee uniqueness, and keep a
-- small set of reserved words free (they collide with app routes like
-- /home and /login).
--
-- Slugs are generated by a trigger on INSERT (and when the name changes
-- and no explicit slug was supplied), so application code never has to
-- set them. Existing rows are backfilled below.

ALTER TABLE groups ADD COLUMN IF NOT EXISTS slug TEXT;

-- Reserved words a group slug must never take (they are app routes or
-- would be confusing). fn_slugify appends a numeric suffix to dodge these
-- just like it does for real collisions.
CREATE OR REPLACE FUNCTION fn_reserved_slugs()
RETURNS TEXT[] AS $$
    SELECT ARRAY['home', 'login', 'logout', 'g', 'api', 'admin',
                 'settings', 'account', 'new', 'create', 'me']::TEXT[];
$$ LANGUAGE sql IMMUTABLE;

-- ------------------------------------------------------------
-- fn_slug_base: name -> bare URL-safe slug (no uniqueness yet)
-- ------------------------------------------------------------
-- Lowercase, ASCII-ish: keep [a-z0-9], turn every run of anything else
-- into a single hyphen, trim leading/trailing hyphens. Empty result (e.g.
-- an all-emoji name) falls back to 'circle'.
CREATE OR REPLACE FUNCTION fn_slug_base(p_name TEXT)
RETURNS TEXT AS $$
DECLARE
    v TEXT;
BEGIN
    v := lower(coalesce(p_name, ''));
    v := regexp_replace(v, '[^a-z0-9]+', '-', 'g');
    v := regexp_replace(v, '(^-+|-+$)', '', 'g');
    IF v IS NULL OR v = '' THEN
        v := 'circle';
    END IF;
    RETURN v;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ------------------------------------------------------------
-- fn_unique_group_slug: base -> unique slug, excluding one row
-- ------------------------------------------------------------
-- Appends -2, -3, ... until the slug is free (and not reserved). The
-- p_exclude_id lets an UPDATE keep its own current slug without colliding
-- with itself.
CREATE OR REPLACE FUNCTION fn_unique_group_slug(p_base TEXT, p_exclude_id UUID)
RETURNS TEXT AS $$
DECLARE
    v_candidate TEXT := p_base;
    v_n INT := 1;
BEGIN
    LOOP
        IF NOT (v_candidate = ANY (fn_reserved_slugs()))
           AND NOT EXISTS (
               SELECT 1 FROM groups
               WHERE slug = v_candidate
                 AND (p_exclude_id IS NULL OR id <> p_exclude_id)
           )
        THEN
            RETURN v_candidate;
        END IF;
        v_n := v_n + 1;
        v_candidate := p_base || '-' || v_n;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Trigger: assign a slug on INSERT / when name changes
-- ------------------------------------------------------------
-- Honours an explicitly-provided slug (slugified + uniquified), otherwise
-- derives one from the name. On UPDATE we only regenerate when the name
-- changed and the caller didn't hand us a new slug, so hand-picked slugs
-- stay stable.
CREATE OR REPLACE FUNCTION fn_set_group_slug()
RETURNS TRIGGER AS $$
DECLARE
    v_base TEXT;
BEGIN
    IF TG_OP = 'INSERT' THEN
        v_base := fn_slug_base(COALESCE(NULLIF(NEW.slug, ''), NEW.name));
        NEW.slug := fn_unique_group_slug(v_base, NULL);
    ELSIF TG_OP = 'UPDATE' THEN
        IF NEW.slug IS DISTINCT FROM OLD.slug AND NULLIF(NEW.slug, '') IS NOT NULL THEN
            -- Caller set an explicit new slug.
            NEW.slug := fn_unique_group_slug(fn_slug_base(NEW.slug), NEW.id);
        ELSIF NEW.name IS DISTINCT FROM OLD.name AND NEW.slug IS NULL THEN
            NEW.slug := fn_unique_group_slug(fn_slug_base(NEW.name), NEW.id);
        ELSE
            NEW.slug := OLD.slug; -- unchanged
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_group_slug ON groups;
CREATE TRIGGER trg_set_group_slug
    BEFORE INSERT OR UPDATE ON groups
    FOR EACH ROW EXECUTE FUNCTION fn_set_group_slug();

-- ------------------------------------------------------------
-- Backfill existing rows (oldest first, so their slugs are the
-- "un-suffixed" ones when names collide).
-- ------------------------------------------------------------
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN SELECT id, name FROM groups WHERE slug IS NULL ORDER BY created_at LOOP
        UPDATE groups
        SET slug = fn_unique_group_slug(fn_slug_base(r.name), r.id)
        WHERE id = r.id;
    END LOOP;
END $$;

-- Now that every row has one, enforce NOT NULL + uniqueness.
ALTER TABLE groups ALTER COLUMN slug SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_groups_slug ON groups (slug);
